export *from './HomePage';
export *from './LoginPage';
export *from './InsuredClaimsPage';
export *from './RegistroPage';
export *from './NewClaimPage';
export *from './AnalistClaimsPage';
export *from './ClaimDetailPage';
export *from './AccidentRatePage';
export *from './PayOrderPage';